// <auto-generated />
namespace BackEnd_Final_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class BookModelSomeChanged : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BookModelSomeChanged));
        
        string IMigrationMetadata.Id
        {
            get { return "202002160018474_BookModel-SomeChanged"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
